<?php
	define("mysqlServer","localhost");
	define("mysqlDB","onlinegame");
	define("mysqlUser","localhost");
	define("mysqlPass","password");
	$hostname="localhost";
	$username="localhost";
	$password="password";
	$dbname="onlinegame";
?>